#### 1. hello world

In [3]:
import tensorflow as tf
message = tf.constant('welcome to the exciting world of Deep Neural Network!')  # 声明为常量，变量为Variable  
with tf.Session() as sess:
    # run执行计算图
    print(sess.run(message).decode())  

welcome to the exciting world of Deep Neural Network!


#### 2.两个向量的和

In [8]:
# 递交的变量
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
#递交的操作
v_add = tf.add(v_1,v_2)
#生成会话
with tf.Session() as sess:
    print(sess.run([v_1,v_add]))  #运行的结果在v_add中提取

[array([1, 2, 3, 4]), array([3, 3, 8, 7])]


###### ps:采用with open 的方式不用close == 

"<br>
sess = tf.Session() <br>
print(sess.run(v_add)) <br>
sess.close()<br>
"

#### 3.简便方式--tf.InteractiveSession()

In [10]:
sess = tf.InteractiveSession()
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
print(v_add.eval())
sess.close()

[3 3 8 7]


#### 4.常量、变量、占位符

In [25]:
# 声明标量常量
t_1 = tf.constant(4)

#  声明向量常量
t_2 = tf.constant([1,3])

# 所以元素都是0的常量
t_zeros = tf.zeros([2,3],tf.int32)

# 所有元素都是1
t_ones = tf.ones([2,3],tf.int32)

# 采用和Numpy一样的like
t_zeros2 = tf.zeros_like(t_2)
t_ones2 = tf.ones_like(t_2)


# 等差数列
range_t1 = tf.linspace(2.0,5,5)  # (star,end,nums)
range_t2 = tf.range(2.0,5.0,0.5) # (star,end,delta),tensorflow对象不可迭代

# 随机数种子
tf.set_random_seed(54)
# 正态分布
normal_t1 = tf.random_normal([2,5],mean=0,stddev=1,seed=12)  #[M,N] shape
#  截尾正态分布
normal_t2 = tf.truncated_normal([2,3],mean=0,stddev=1,seed=12)
# 伽马分布随机数
gamma_t = tf.random_uniform([2,3],maxval=4,seed=12)



# 对已有张量进行操作
new_t1 = tf.random_crop(normal_t1,[2,3],seed=12)  #裁剪出一个大小为 [2，5] 的张量。
new_t2 = tf.random_shuffle(normal_t1)    # 洗牌操作


sess = tf.InteractiveSession()
print(range_t1.eval(),t_2.eval(),range_t2.eval())
print(normal_t1.eval())
print(new_t1.eval())
print(new_t2.eval())
sess.close()

[2.   2.75 3.5  4.25 5.  ] [1 3] [2.  2.5 3.  3.5 4.  4.5]
[[-1.8324823  1.2200226  1.1031684  1.6486678 -2.1511295]
 [ 2.1331878 -1.3384562 -0.4609988  0.6739213  1.0025555]]
[[-0.3898768  -0.94399023 -1.320119  ]
 [-0.48511508  1.263194    0.95144075]]
[[ 0.01493934 -1.5585597  -0.58463776 -0.47615474 -1.0048292 ]
 [ 1.0039591  -0.37774724  1.5660077  -0.8490109  -0.17765619]]


D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


#### 5.变量 -- 需要初始化

In [29]:
rand_t = tf.random_uniform([50,50],0,10,seed=0)  #定义一个随机数生成器
weights = tf.Variable(rand_t,name='ws')
bs = tf.Variable(rand_t,name='bs')


# 简单例子一,向量乘法
# creat a variable
w = tf.Variable([[0.5,1.0]]) # 行向量 1*2
x = tf.Variable([[2.0],[1.0]]) # 列向量 2*1

y = tf.matmul(w,x)


# 初始化变量
init_op = tf.global_variables_initializer()

# 会话
with tf.Session() as sess:
    sess.run(init_op)   #操做
    print(y.eval())

[[2.]]


#### 6.占位符

In [ ]:
x = tf.placeholder("fload")
y = 2*x
data = tf.random_uniform([4,5],10)
with tf.Session() as sess:
    x_data = sess.run(data)  # 获得x_data数据
    print(sess.run(y,feed_dict={x:x_data}))  # 将数据传入占位符

#### 7.矩阵

In [36]:
import tensorflow as tf
sess = tf.InteractiveSession()  #创建会话

# 5x5 单位 matrix
I_matrix = tf.eye(5)
print(I_matrix.eval())

# Variable
X = tf.Variable(tf.eye(10))
X.initializer.run()  #初始化
print(X.eval())

# random 5x10 matrix
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()

# mutiply
product = tf.matmul(A,X)
print(product.eval())

#b_new=tf.cast(b,dtype=tf.int32)  将b的数据类型变为int32


B = tf.Variable(tf.random_normal([5,10]))
B.initializer.run()
#矩阵相加和相减
#t_sum = tf.add(A,B) == A + B
#t_sub = A - B


# 对应元素相乘
S = A * B
# 放缩
S1 = tf.scalar_mul(2,A)  #A 每个元素放大2倍
# 除法
# S2 = tf.div(A,B)
# 取模
S3 = tf.mod(A,B)


sess.close()

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[ 1.0409329e-01  1.7612766e-01  4.0092114e-01 -4.7359362e-01
  -8.9008081e-01 -3.2931033e-01  1.1805335e+00 -7.4498290e-01
  -5.3467947e-01 -3.2709023e-01]
 [-1.0903871e+00 -4.5062423e-01 -1.0952277e+00 -2.0352075e+00
   8.9649904e-01 -6.4399093e-01  9.0725553e-01  1.5119251e+00
   1.9310859e+00 -1.8151686e-01]
 [ 4.8359025e-01 -3.6523750e-01 -9.3610687e-03  2.3846766e-01
  -5.7576794e-02 -2.9349419e-01  7.1988559e-01  2.8593734e-01
  -5.6753451e-01  9.3321717e-01]
 [ 1.9533842e+00 -7.5417733e-01 -1.6613606e+00 -1.3091313e+00
  -9.9098772e-01  1.8286766e-01 -3.5699734e-0

D:\Anaconda\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


### Board

In [40]:
import tensorflow as tf

rand_t = tf.random_uniform([50,50],0,10,seed=0)  #定义一个随机数生成器
input_tensor = tf.Variable(rand_t,name='its')
weights = tf.Variable(rand_t,name='ws')
bs = tf.Variable(rand_t,name='bs')

output_tensor = tf.matmul(input_tensor,weights)+bs
with tf.Session() as sess:
    tf.summary.histogram('out_put',output_tensor)
    tf.summary.FileWriter('summary_dir',sess.graph)